# Generated by Django 6.0.3 on 2026-04-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.JSONField(blank=True, default=list, verbose_name='Danh sách màu (JSON: name, hex)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.JSONField(blank=True, default=list, verbose_name='Danh sách size (JSON list)'),
        ),
    ]
