# Generated by Django 6.0.4 on 2026-04-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('shipping', 'Đang vận chuyển'), ('completed', 'Hoàn thành'), ('return', 'Trả hàng/Hoàn tiền')], default='shipping', max_length=20),
        ),
    ]
